BaseDeConhecimento/BaseDeConhecimento/Controllers/AspectoProjetoController.cs
using BaseDeConhecimento.Dtos;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaseDeConhecimento.Models;

namespace BaseDeConhecimento.Controllers
{
    public class AspectoProjetoController : Controller
    {
        //
        // GET: /AspectoProjeto/

        public ActionResult Index(int id)
        {
            ViewBag.idProjeto = id;
            return View(AspectoBO.getAspectosPorProjeto(id));
        }

        public ActionResult Cadastrar(int id)
        {
            ViewBag.listAspectos = AspectoDTO.SelectAspectos;

            AspectoProjetoDTO dto = new AspectoProjetoDTO() { idProjeto = id.ToString(),nomeProjeto = ProjetoBO.GetPorId(id).titulo  };
            return View(dto);
        }

        public ActionResult Salvar(FormCollection dadosAspecto)
        {
            string[] vetorIdAspecto = dadosAspecto["hdIdAspecto[]"].Split(',');
            string[] vetorValorAspecto = dadosAspecto["hdValorAspecto[]"].Split(',');
            string[] vetorPrioridade = dadosAspecto["hdPrioridade[]"].Split(',');

            List<AspectoProjetoDTO> aspectoProjeto = new List<AspectoProjetoDTO>();

            for (int i = 0; i < vetorIdAspecto.Count(); i++)
            {
                aspectoProjeto.Add(new AspectoProjetoDTO() { idProjeto = dadosAspecto["idProjeto"], idAspecto = vetorIdAspecto[i], valorAtribuido = vetorValorAspecto[i], prioridade = vetorPrioridade[i] });
            }

            
            AspectoBO.adicionarAspectoPorProjeto(aspectoProjeto);
            ViewBag.Destino = string.Concat(HttpContext.Request.Url.Scheme, "://", HttpContext.Request.Url.Authority, "/AspectoProjeto/Index/", int.Parse(dadosAspecto["idProjeto"]));
            return View("Sucesso");
        }
    }
}

BaseDeConhecimento/BaseDeConhecimento/Controllers/ProjetoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaseDeConhecimento.Dtos;
using BaseDeConhecimento.Models;
using System.Drawing;
using System.Globalization;
namespace BaseDeConhecimento.Controllers
{
    public class ProjetoController : Controller
    {
        //
        // GET: /Projeto/

        public ActionResult Cadastrar()
        {
            return View("Cadastrar");
        }

        public ActionResult Editar()
        {
            return View();
        }

        public ActionResult Salvar(FormCollection dadosProjeto)
        {
            ProjetoDTO projetoDto = new ProjetoDTO()
            {
                custoPrevisto = dadosProjeto["custoPrevisto"],
                custoReal = dadosProjeto["custoReal"],
                dataFim = dadosProjeto["dataFim"],
                dataInicio = dadosProjeto["dataInicio"],
                dataPrevistaInicio = dadosProjeto["dataPrevistaInicio"],
                dataPrevistaTermino = dadosProjeto["dataPrevistaTermino"],
                descricao = dadosProjeto["descricao"],
                titulo = dadosProjeto["titulo"]
            };

            ProjetoBO.Salvar(projetoDto);
            
            return View("Sucesso");
        }

        public ActionResult Listar()
        {
            
            return View(ProjetoBO.GetAll());
        }

    }
}

BaseDeConhecimento/BaseDeConhecimento/Controllers/UsuarioPorTecnologiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseDeConhecimento.Controllers
{
    public class UsuarioPorTecnologiaController : Controller
    {
        //
        // GET: /UsuarioPorTecnologia/

        public ActionResult Index()
        {
            return View();
        }

    }
}

BaseDeConhecimento/BaseDeConhecimento/Views/Projeto/Cad.cshtml
@model BaseDeConhecimento.Models.Projeto

@{
    ViewBag.Title = "Cad";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cad</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Projeto</legend>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BaseDeConhecimento/BaseDeConhecimento/Views/Projeto/Cadastrar.cshtml
@model BaseDeConhecimento.Dtos.ProjetoDTO
@{
    ViewBag.Title = "Cadastrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cadastrar</h2>

@using (Html.BeginForm("Salvar", "Projeto"))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Projeto</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.titulo):&nbsp;&nbsp;@Html.EditorFor(model => model.titulo)
            @Html.ValidationMessageFor(model => model.titulo)
        </div>
        <div class="editor-label">
            @Html.LabelFor(model => model.descricao):&nbsp;&nbsp; @Html.EditorFor(model => model.descricao)
            @Html.ValidationMessageFor(model => model.descricao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dataPrevistaInicio):&nbsp;&nbsp; @Html.EditorFor(model => model.dataPrevistaInicio)
            &nbsp;&nbsp;&nbsp;&nbsp;
            @Html.LabelFor(model => model.dataPrevistaTermino):&nbsp;&nbsp; @Html.EditorFor(model => model.dataPrevistaTermino)
            @Html.ValidationMessageFor(model => model.dataPrevistaTermino)
             @Html.ValidationMessageFor(model => model.dataPrevistaInicio)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.custoPrevisto):&nbsp;&nbsp;@Html.EditorFor(model => model.custoPrevisto)
           
            &nbsp;&nbsp;&nbsp;&nbsp;
            @Html.LabelFor(model => model.custoReal):&nbsp;&nbsp; @Html.EditorFor(model => model.custoReal)
            @Html.ValidationMessageFor(model => model.custoReal)
             @Html.ValidationMessageFor(model => model.custoPrevisto)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.dataInicio):&nbsp;&nbsp; @Html.EditorFor(model => model.dataInicio)
            &nbsp;&nbsp; &nbsp;&nbsp;
             @Html.LabelFor(model => model.dataFim):&nbsp;&nbsp;@Html.EditorFor(model => model.dataFim)
            @Html.ValidationMessageFor(model => model.dataInicio)
            @Html.ValidationMessageFor(model => model.dataFim)
        </div>
       
       
        <p>
            <input type="submit" value="Salvar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Listar todos", "Listar")
</div>
<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Views/Projeto.js")" type="text/javascript"></script>

BaseDeConhecimento/BaseDeConhecimento/Views/Projeto/Listar.cshtml
@model IEnumerable<BaseDeConhecimento.Dtos.ProjetoDTO>
@{
    ViewBag.Title = "Listar2";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Listar2</h2>

<p>
    @Html.ActionLink("Novo", "Cadastrar")
</p>
<table>
    <tr>
        <th></th>
        <th>Título
        </th>
        <th>Descrição
        </th>
        <th>Data prevista inicio
        </th>
        <th>Data prevista término
        </th>
        <th>Custo previsto
        </th>
        <th>Custo real
        </th>
        <th>Data inicio
        </th>
        <th>Data fim
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idProjeto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.titulo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dataPrevistaInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dataPrevistaTermino)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.custoPrevisto)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.custoReal)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dataInicio)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dataFim)
            </td>
            <td>
                @Html.ActionLink("Requisitos", "Index", "Requisito", new { id = item.idProjeto }, null) |
                @Html.ActionLink("Usuários/Tecnologia", "Index", "UsuarioPorTecnologia", new { id = item.idProjeto }, null) |
                @Html.ActionLink("Aspectos", "Index", "AspectoProjeto", new { id = item.idProjeto }, null)
            </td>
        </tr>
    }

</table>