BaseDeConhecimento/BaseDeConhecimento/Controllers/TecnologiaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaseDeConhecimento.Dtos;
using BaseDeConhecimento.Models;

namespace BaseDeConhecimento.Controllers
{
    public class TecnologiaController : Controller
    {
        //
        // GET: /Tecnologia/

        public ActionResult Index()
        {
            return View(TecnologiaBO.GetAll());
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        public ActionResult Salvar(FormCollection dadosProjeto)
        {
            TecnologiaDto tecnologiaDto = new TecnologiaDto() { nome = dadosProjeto["nome"] };
            TecnologiaBO.Salvar(tecnologiaDto);

            return View("Sucesso");
        }

    }
}

BaseDeConhecimento/BaseDeConhecimento/Views/Tecnologia/Cadastrar.cshtml
@model BaseDeConhecimento.Dtos.TecnologiaDto

@{
    ViewBag.Title = "Cadastrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cadastrar</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Salvar","Tecnologia")) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>TecnologiaDto</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nome)
            @Html.ValidationMessageFor(model => model.nome)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BaseDeConhecimento/BaseDeConhecimento/Views/Tecnologia/Index.cshtml
@model IEnumerable<BaseDeConhecimento.Dtos.TecnologiaDto>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Nova tecnologia", "Cadastrar")
</p>
<table>
    <tr>
        <th>Nome
        </th>
        <th></th>
    </tr>
    @if (Model != null)
    {
        foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new {  id=item.id  })
                @Html.ActionLink("Excluir", "Delete", new {  id=item.id  })
            </td>
        </tr>
        }
    }

</table>