BaseDeConhecimento/BaseDeConhecimento/Controllers/AtividadeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BaseDeConhecimento.Controllers
{
    public class AtividadeController : Controller
    {
        //
        // GET: /Atividade/

        public ActionResult Index()
        {
            return View();
        }

    }
}

BaseDeConhecimento/BaseDeConhecimento/Controllers/RequisitoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaseDeConhecimento.Dtos;
using BaseDeConhecimento.Models;

namespace BaseDeConhecimento.Controllers
{
    public class RequisitoController : Controller
    {
        //
        // GET: /Requisito/

        public ActionResult Index(int id)
        {
            ViewBag.idProjeto = id;
            return View(RequisitoBO.GetRequisitosPorProjeto(id));
        }

        public ActionResult Cadastrar(int id)
        {
            ViewBag.idProjeto = id;
            return View();
        }


        public ActionResult Salvar(FormCollection dadosRequisito)
        {
            //ViewBag.idProjeto = id;
            RequisitoDTO requisitoDto = new RequisitoDTO()
            {
                bugs = dadosRequisito["bugs"],
                qtdComunicacaoExterna = dadosRequisito["qtdComunicacaoExterna"],
                nome = dadosRequisito["nome"],
                descricao = dadosRequisito["descricao"],
                idProjeto = int.Parse(dadosRequisito["hdIdProjeto"]),
                criterioAceitacao = dadosRequisito["criterioAceitacao"]
            };

            if (string.IsNullOrEmpty(dadosRequisito["idRequisito"]))
            {
                RequisitoBO.Salvar(requisitoDto);
                ViewBag.Destino = string.Concat(HttpContext.Request.Url.Scheme,"://",HttpContext.Request.Url.Authority, "/Requisito/Index/",requisitoDto.idProjeto);
                return View("Sucesso");
            }
            else
            {
                requisitoDto.idRequisito = int.Parse(dadosRequisito["idRequisito"]);
                RequisitoBO.Editar(requisitoDto);
                return RedirectToAction("Index", "Requisito", new { id = requisitoDto.idProjeto });
            }
        }

        public ActionResult Editar(int id)
        {
            return View(RequisitoBO.GetRequisito(id));
        }

    }
}

BaseDeConhecimento/BaseDeConhecimento/Views/Requisito/Cadastrar.cshtml
@model BaseDeConhecimento.Dtos.RequisitoDTO
@{
    ViewBag.Title = "Cadastrar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Cadastrar</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/Views/Requisito.js")" type="text/javascript"></script>


@using (Html.BeginForm("Salvar", "Requisito"))
{
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>RequisitoDTO</legend>
        <input type="hidden" value="@ViewBag.idProjeto" id="hdIdProjeto" name="hdIdProjeto"/>

        <div class="editor-label">
            @Html.LabelFor(model => model.nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nome)
            @Html.ValidationMessageFor(model => model.nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.descricao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.descricao)
            @Html.ValidationMessageFor(model => model.descricao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.criterioAceitacao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.criterioAceitacao)
            @Html.ValidationMessageFor(model => model.criterioAceitacao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.bugs)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.bugs)
            @Html.ValidationMessageFor(model => model.bugs)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.qtdComunicacaoExterna)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.qtdComunicacaoExterna)
            @Html.ValidationMessageFor(model => model.qtdComunicacaoExterna)
        </div>
       
        <p>
            <input type="submit" value="Salvar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BaseDeConhecimento/BaseDeConhecimento/Views/Requisito/Editar.cshtml
@model BaseDeConhecimento.Dtos.RequisitoDTO

@{
    ViewBag.Title = "Editar";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Editar</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm("Salvar", "Requisito")) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>RequisitoDTO</legend>

        <div class="editor-label">
            @Html.HiddenFor(model => model.idRequisito)
             <input type="hidden" value="@Model.idProjeto" id="hdIdProjeto" name="hdIdProjeto"/>
        </div>
        
        <div class="editor-label">
            @Html.LabelFor(model => model.nome)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.nome)
            @Html.ValidationMessageFor(model => model.nome)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.descricao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.descricao)
            @Html.ValidationMessageFor(model => model.descricao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.criterioAceitacao)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.criterioAceitacao)
            @Html.ValidationMessageFor(model => model.criterioAceitacao)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.bugs)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.bugs)
            @Html.ValidationMessageFor(model => model.bugs)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.qtdComunicacaoExterna)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.qtdComunicacaoExterna)
            @Html.ValidationMessageFor(model => model.qtdComunicacaoExterna)
        </div>
        <p>
            <input type="submit" value="Atualizar" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

BaseDeConhecimento/BaseDeConhecimento/Views/Requisito/Index.cshtml
@model IEnumerable<BaseDeConhecimento.Dtos.RequisitoDTO>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Novo", "Cadastrar", new { id = @ViewBag.idProjeto })
</p>
<table>
    <tr>
        <th></th>
        <th>Nome
        </th>
        <th>Descricao
        </th>
        <th>Critério de aceitacao
        </th>
        <th>Qtd. Bugs
        </th>
        <th>Qtd. Comunicacao Externa
        </th>
        <th>Data Cadastro
        </th>
        <th></th>
    </tr>

    @if (Model != null)
    {
        foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.idRequisito)
            </td>

            <td>
                @Html.DisplayFor(modelItem => item.nome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.descricao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.criterioAceitacao)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.bugs)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.qtdComunicacaoExterna)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.dataCadastro)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.idRequisito }, null) |
                @Html.ActionLink("Atividades", "Index", "Atividade", new { idRequisito = item.idRequisito }) |
                
            </td>
        </tr>
        }
    }

</table>