BaseDeConhecimento/BaseDeConhecimento/Controllers/AspectoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaseDeConhecimento.Dtos;
using BaseDeConhecimento.Models;
namespace BaseDeConhecimento.Controllers
{
    public class AspectoController : Controller
    {
        //
        // GET: /Aspecto/

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Cadastrar()
        {
            return View();
        }

        public ActionResult Salvar(FormCollection dadosAspecto)
        {
            AspectoDTO aspectoDto = new AspectoDTO()
            {
                descricao = dadosAspecto["descricao"],
                codigoIdentificacao = dadosAspecto["codigoIdentificacao"],
                tipo = dadosAspecto["tipo"],
                peso = dadosAspecto["peso"]
            };

            AspectoBO.Salvar(aspectoDto);
            return View("Sucesso");
        }

    }
}

BaseDeConhecimento/BaseDeConhecimento/Controllers/ColaboradorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaseDeConhecimento.Models;
using BaseDeConhecimento.Dtos;

namespace BaseDeConhecimento.Controllers
{
    public class ColaboradorController : Controller
    {
        //
        // GET: /Colaborador/

        public ActionResult Index()
        {
            return View(ColaboradorBO.GetAll());
        }

        public ActionResult Cadastrar()
        {
            return View();
        }


        public ActionResult Salvar(FormCollection dadosUsuario)
        {
            ColaboradorDTO colaboradorDto = new ColaboradorDTO()
            {
                email = dadosUsuario["email"],
                nome = dadosUsuario["nome"]
            };

            ColaboradorBO.Salvar(colaboradorDto);
            return View("Sucesso");
        }

    }
}

BaseDeConhecimento/BaseDeConhecimento/Controllers/ProjetoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using BaseDeConhecimento.Dtos;
using BaseDeConhecimento.Models;
using System.Drawing;
using System.Globalization;
namespace BaseDeConhecimento.Controllers
{
    public class ProjetoController : Controller
    {
        //
        // GET: /Projeto/

        public ActionResult Cadastrar()
        {
            return View("Cadastrar");
        }

        public ActionResult Editar()
        {
            return View();
        }

        public ActionResult Salvar(FormCollection dadosProjeto)
        {
            ProjetoDTO projetoDto = new ProjetoDTO()
            {
                custoPrevisto = dadosProjeto["custoPrevisto"],
                custoReal = dadosProjeto["custoReal"],
                dataFim = dadosProjeto["dataFim"],
                dataInicio = dadosProjeto["dataInicio"],
                dataPrevistaInicio = dadosProjeto["dataPrevistaInicio"],
                dataPrevistaTermino = dadosProjeto["dataPrevistaTermino"],
                descricao = dadosProjeto["descricao"],
                titulo = dadosProjeto["titulo"]
            };

            ProjetoBO.Salvar(projetoDto);
            
            return View("Sucesso");
        }

        public ActionResult Listar()
        {
            
            return View(ProjetoBO.GetAll());
        }

    }
}

BaseDeConhecimento/BaseDeConhecimento/Views/Shared/Sucesso.cshtml
@{
    ViewBag.Title = "Sucesso";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Sucesso</h2>

<h3>Cadastro efetuado com sucesso!</h3>

<div>
   <a href="@ViewBag.Destino">Voltar</a>
</div>

BaseDeConhecimento/BaseDeConhecimento/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <title>@ViewBag.Title</title>
    <link href="@Url.Content("~/Content/Site.css")" rel="stylesheet" type="text/css" />
     <link href="@Url.Content("~/Content/jquery-ui/cupertino/jquery-ui-1.10.3.custom.css")" rel="stylesheet" />
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.2.custom.js")" type="text/javascript"></script>
    <script src="@Url.Content("~/Scripts/modernizr-2.5.3.js")" type="text/javascript"></script>
   
</head>
<body>
    <div class="page">
        <header>
            <div id="title">
                <h1>My MVC Application</h1>
            </div>
            <div id="logindisplay">
                @Html.Partial("_LogOnPartial")
            </div>
            <nav>
                <ul id="menu">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                     <li>@Html.ActionLink("Aspectos", "Index", "Aspecto")</li>
                    <li>@Html.ActionLink("Tecnologia", "Index", "Tecnologia")</li>
                    <li>@Html.ActionLink("Projetos", "Listar", "Projeto")</li>
                    <li>@Html.ActionLink("Colaboradores", "Index", "Colaborador")</li>
                </ul>
            </nav>
        </header>
        <section id="main">
            @RenderBody()
        </section>
        <footer>
        </footer>
    </div>
</body>
</html>

BaseDeConhecimento/BaseDeConhecimento/Views/Shared/_LogOnPartial.cshtml
@if(Request.IsAuthenticated) {
    <text>Welcome <strong>@User.Identity.Name</strong>!
    [ @Html.ActionLink("Log Off", "LogOff", "Account") ]</text>
}
else {
    @:[ @Html.ActionLink("Log On", "LogOn", "Account") ]
}